### ISSUE TITLE
DamerauLevenshtein fails with cyrillic words

### ISSUE THREAD

**Issue by symb10z** [maxbachmann/rapidfuzz-rs#4]
I've got error in polars-ds, which uses RapidFuzz as backend, so i think it is RapidFuzz issue:
```shell
thread '<unnamed>' panicked at /home/symbioz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rapidfuzz-0.3.0/src/details/growing_hashmap.rs:118:19:
index out of bounds: the len is 8 but the index is 61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The plugin panicked which is unrecoverable. Polars will abort
Aborte
``` 

Here is Python code used:

```python
import polars as pl
from polars_ds import StrExt
word_pairs=pl.DataFrame(
    {
        "char1":['Иванко'],
        "char2":['Петрунко']
    }
)
word_pairs=word_pairs.with_columns(pl.col("char1").str_ext.d_levenshtein(pl.col("char2"),parallel=True).alias("distance_ds"))
print(word_pairs)
``` 

For reference:
[https://github.com/abstractqqq/polars_ds_extension/issues/24](url)

**Comment by maxbachmann** [comment]
Thanks for reporting. I fixed this in https://github.com/maxbachmann/rapidfuzz-rs/commit/0f402862495c5430e8fb10991bd0e7cbbb873c2f and published version `0.3.1` with the fix.

**Comment by symb10z** [comment]
Above sample was fixed, but now it fails when we have mixed cyrillic and latin:
```python
import polars as pl
from polars_ds import StrExt
word_pairs=pl.DataFrame(
    {
        "char1":['ИванкоIvan'],
        "char2":['Петрунко']
    }
)
word_pairs=word_pairs.with_columns(pl.col("char1").str_ext.d_levenshtein(pl.col("char2"),parallel=True).alias("distance_ds"))
print(word_pairs)
``` 
Error:
```shell
thread '<unnamed>' panicked at /home/bulych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rapidfuzz-0.3.1/src/details/growing_hashmap.rs:110:15:
index out of bounds: the len is 8 but the index is 15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The plugin panicked which is unrecoverable. Polars will abort
Aborted
```

**Comment by maxbachmann** [comment]
Another unrelated bug in the same code section :man_facepalming: 
I must have slept when porting this section over. Fixed in https://github.com/maxbachmann/rapidfuzz-rs/commit/2221ce472cfbe773c8e355c21f4b0320828ad61e.

I really have to get fuzz tests up and running in rust as well.
